/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Semana_11.Tarea;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Detz1
 */
class Metodo{
        
    static int nAleatorio(int min, int max){ // DEVUELVE UN NUMERO ALEATORIO
        int n;
        Random rd=new Random();
        n=rd.nextInt((max-min)+1)+min;
        return n;      
    }
    void rellenarVector(int vector[]){
        for (int i = 0; i <vector.length ; i++) {
            vector[i]=nAleatorio(1,20);
        }
    }
    
    String printVector(int vector[]){ 
        String x="";
        for(Integer i:vector){
         x+=" [ "+i+" ]";  
        }
        return x;
    }
    
    int sum_Recursivo(int vector[],int n) {
            int rta;
            if (n == 0){
                return vector[n];
            }else{
                 rta =  vector[n] +  sum_Recursivo( vector,(n-1));
            }
            return rta;
        }
    
    int sum_Iterativo(int vector[]){
        int sum=0;
        for (int i = 0; i < vector.length; i++) {
            sum +=vector[i];
        }
        
        return sum;
    }
}

public class Trabajo extends javax.swing.JFrame {
    
    Metodo metodo =new Metodo();
    int [] array;
    DefaultTableModel model = new DefaultTableModel();
    
    
    public Trabajo() {
        initComponents();
        buttonGroup1.add(btn_recursivo);
        buttonGroup1.add(btn_iterativo);
        model.addColumn("Tamaño");
        model.addColumn("Tipo");
        model.addColumn("Inicio");
        model.addColumn("Fin");
        model.addColumn("Resultado");
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_titulo = new javax.swing.JLabel();
        nelementos = new javax.swing.JTextField();
        lbl_nelementos = new javax.swing.JLabel();
        btn_data = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_elementos = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        n_tabla = new javax.swing.JTable();
        btn_recursivo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btn_iterativo = new javax.swing.JRadioButton();
        btn_run = new javax.swing.JButton();
        lbl_tipo = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        lbl_titulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_titulo.setText("SUMA DE ELEMENTOS DE UN VECTOR");

        lbl_nelementos.setText("Numero de elementos: ");

        btn_data.setText("Generar Data");
        btn_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataActionPerformed(evt);
            }
        });

        text_elementos.setColumns(20);
        text_elementos.setRows(5);
        jScrollPane1.setViewportView(text_elementos);

        n_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tamaño", "Tipo", "Inicio", "FIN", "Resultado"
            }
        ));
        jScrollPane3.setViewportView(n_tabla);

        btn_recursivo.setText("Recursivo");

        btn_iterativo.setText("Iterativo");

        btn_run.setText("Realizar");
        btn_run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_runActionPerformed(evt);
            }
        });

        lbl_tipo.setText("Tipo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_nelementos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nelementos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(btn_data))
                                    .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btn_recursivo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_iterativo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_run, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(11, 11, 11)))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nelementos)
                    .addComponent(nelementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_data)
                    .addComponent(jLabel1)
                    .addComponent(lbl_tipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_recursivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_iterativo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_run))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void btn_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataActionPerformed
        this.text_elementos.setText("");
        int n=Integer.parseInt(this.nelementos.getText().trim());
        array= new int[n];
        
        metodo.rellenarVector(array);
        this.text_elementos.setText(metodo.printVector(array));
        this.nelementos.setText("");    
    }//GEN-LAST:event_btn_dataActionPerformed

    private void btn_runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_runActionPerformed
        long inicio=0;
        long fin=0;
        long resultado= 0;
        
        
        if(btn_recursivo.isSelected()){
            int z= array.length;    
            inicio=System.nanoTime();
            resultado=metodo.sum_Recursivo(array, (z-1));
            fin=System.nanoTime();
            this.text_elementos.setText(metodo.printVector(array)+" = "+resultado);
            model.addRow(new Object[]{array.length,"Recursivo",inicio,fin,fin-inicio});
            
        }else if(btn_iterativo.isSelected()){    
            inicio=System.nanoTime();
            resultado=metodo.sum_Iterativo(array);
            fin=System.nanoTime();
    
            this.text_elementos.setText(metodo.printVector(array)+" = "+resultado);
             model.addRow(new Object[]{array.length,"Iterativo",inicio,fin,fin-inicio});
        }else{
                JOptionPane.showMessageDialog(null, "SIN SELECCION");
                }
        n_tabla.setModel(model);
    }//GEN-LAST:event_btn_runActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trabajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_data;
    private javax.swing.JRadioButton btn_iterativo;
    private javax.swing.JRadioButton btn_recursivo;
    private javax.swing.JButton btn_run;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_nelementos;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTable n_tabla;
    private javax.swing.JTextField nelementos;
    private javax.swing.JTextArea text_elementos;
    // End of variables declaration//GEN-END:variables
}
